// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4uv08UaXi-KBdkCzU2AVP4Yn_rrSxalI',
    appId: '1:284490692386:web:025f4c85080762e52c177b',
    messagingSenderId: '284490692386',
    projectId: 'b6arya-485bc',
    authDomain: 'b6arya-485bc.firebaseapp.com',
    storageBucket: 'b6arya-485bc.appspot.com',
    measurementId: 'G-CWZX9X586C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIRXe6jtTabR25MoIz5p3F6llp8GorDxk',
    appId: '1:284490692386:android:ddd351c397f671732c177b',
    messagingSenderId: '284490692386',
    projectId: 'b6arya-485bc',
    storageBucket: 'b6arya-485bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-jwe8Nz7VK6s9nYbSk4pkYFSAecOXOcc',
    appId: '1:284490692386:ios:da37299a9443d91b2c177b',
    messagingSenderId: '284490692386',
    projectId: 'b6arya-485bc',
    storageBucket: 'b6arya-485bc.appspot.com',
    iosBundleId: 'com.battery.b6arya',
  );
}
